spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: scott
    password: tiger

  jpa:
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: true
